### ISSUE TITLE
Replace cargo-generate with kickstart

### ISSUE THREAD

**Issue by eupn** [knurling-rs/app-template#36]
I think it could be better to replace `cargo-generate` with a similar but more powerful tool [`kickstart`](https://github.com/Keats/kickstart). This tool supports custom template variables. This should free user of most of the manual actions of replacing `{{variables}}` that aren't supported by cargo-generate.

If it makes sense to do so, I'll be happy to make a PR for this.

**Comment by jonas-schievink** [comment]
I think I'm on board with this. This seems like a straightforward way to improve the experience.

We are also thinking about making a more elaborate embedded-specific project creation tool, but that's definitely a longer-term project, so this seems like a good intermediate step.

**Comment by Mitchelldscott** [comment]
I've been setting up a `cargo-generate` template and wondering if this is still in the works? I was able to setup variable substitution like so:
### 1. Create a cargo-generate.toml

```toml
[template]
description = "A Cargo workspace for embedded targets"

[placeholders.hal_crate] 
type = "string"
prompt = "Select a HAL"
choices = ["stm32f4xx-hal", "imxrt-hal", "rp2040-hal"]
default = "stm32f4xx-hal"

[hooks]
post = "add_hal.rhai"
```

### 2. Implement a post-script to add the hal

```rhai
let hal = variable::get("hal_crate");

print("Adding HAL crate: " + hal);
print(system::command("cargo", ["add", hal]));
```

### 3. In the workspace manifest

```toml
[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2024"
authors = [ "{{authors}}" ]
```

### 4. Implementation with generic HAL selection
Create a file `src/main.rs.liquid`
```txt
#![no-std]
#![no-main]

use {{hal_crate}} as hal;

#[unsafe(no_mangle)]
pub extern "C" fn _start() -> ! {
    
}
```

### 5. Generate a workspace

````bash
cargo install cargo-generate
cargo generate \
  --git git@github.com:mitchelldscott/cargo-workspace-demo \
  templates/demo-template \
  -d hal_crate=imxrt-hal \
  --name hal-demo
````
